#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#npm run pre-commit
npx pretty-quick --pattern "src/**/**.ts" --pattern "src/**/**.json" --pattern "src/**/**.html"  --pattern "src/**/**.scss"  --staged --verbose && ng lint --fix